# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true
  packages: !include_dir_named packages

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.elegoo_printer: debug

default_config:
